// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

public partial class ESD_DBContext : DbContext
{
    public ESD_DBContext(DbContextOptions<ESD_DBContext> options)
        : base(options)
    {
    }

    //public virtual DbSet<ESDMachine> ESDMachine { get; set; }

    //public virtual DbSet<PPORTAL_QUAL01_INFO> PPORTAL_QUAL01_INFO { get; set; }

    //public virtual DbSet<PPORTAL_QUAL02_INFO> PPORTAL_QUAL02_INFO { get; set; }

    //public virtual DbSet<PPORTAL_QUAL02_POLICY> PPORTAL_QUAL02_POLICY { get; set; }

    public virtual DbSet<sysTbl_Application> sysTbl_Application { get; set; }

    public virtual DbSet<sysTbl_CommonDetail> sysTbl_CommonDetail { get; set; }

    public virtual DbSet<sysTbl_CommonMaster> sysTbl_CommonMaster { get; set; }

    public virtual DbSet<sysTbl_Document> sysTbl_Document { get; set; }

    public virtual DbSet<sysTbl_Menu> sysTbl_Menu { get; set; }

    public virtual DbSet<sysTbl_Menu_Permission> sysTbl_Menu_Permission { get; set; }

    public virtual DbSet<sysTbl_NotificationToken> sysTbl_NotificationToken { get; set; }

    public virtual DbSet<sysTbl_RefreshToken> sysTbl_RefreshToken { get; set; }

    public virtual DbSet<sysTbl_Role> sysTbl_Role { get; set; }

    public virtual DbSet<sysTbl_Role_Menu> sysTbl_Role_Menu { get; set; }

    public virtual DbSet<sysTbl_Role_Menu_Permission> sysTbl_Role_Menu_Permission { get; set; }

    public virtual DbSet<sysTbl_User> sysTbl_User { get; set; }

    public virtual DbSet<sysTbl_User_Role> sysTbl_User_Role { get; set; }

    //protected override void OnModelCreating(ModelBuilder modelBuilder)
    //{
    //    modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AI");

    //    modelBuilder.Entity<ESDMachine>(entity =>
    //    {
    //        entity.HasKey(e => e.MachineId).HasName("PK_Machine_MachineId");

    //        entity.Property(e => e.MachineId).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();
    //    });

    //    //modelBuilder.Entity<PPORTAL_QUAL01_INFO>(entity =>
    //    //{
    //    //    entity.HasKey(e => e.Id).HasName("PK_pportal_qual01_info");
    //    //});

    //    //modelBuilder.Entity<PPORTAL_QUAL02_INFO>(entity =>
    //    //{
    //    //    entity.HasKey(e => e.Id).HasName("PK_pportal_qual02_info_1");

    //    //    entity.Property(e => e.reg_dt).HasDefaultValueSql("(getdate())");
    //    //});

    //    //modelBuilder.Entity<PPORTAL_QUAL02_POLICY>(entity =>
    //    //{
    //    //    entity.HasKey(e => e.Id).HasName("PK_pportal_qual02_policy");

    //    //    entity.Property(e => e.Id).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //    //    entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //    //    entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //    //    entity.Property(e => e.row_version)
    //    //        .IsRowVersion()
    //    //        .IsConcurrencyToken();
    //    //});

    //    modelBuilder.Entity<sysTbl_Application>(entity =>
    //    {
    //        entity.Property(e => e.id_app).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.change_date).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();
    //        entity.Property(e => e.update_type).HasDefaultValueSql("((0))");
    //    });

    //    modelBuilder.Entity<sysTbl_CommonDetail>(entity =>
    //    {
    //        entity.HasKey(e => e.commonDetailId).HasName("PK_sysTbl_CommonMasterDetail");

    //        entity.Property(e => e.commonDetailId).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();

    //        entity.HasOne(d => d.commonMasterCodeNavigation).WithMany(p => p.sysTbl_CommonDetail).HasConstraintName("fk_CommonDetail_CommonMaster_commonMasterCode");
    //    });

    //    modelBuilder.Entity<sysTbl_CommonMaster>(entity =>
    //    {
    //        entity.HasKey(e => e.commonMasterCode).HasName("PK_sysTbl_CommonMaster_commonMasterCode");

    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.forRoot).HasDefaultValueSql("((0))");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();
    //    });

    //    modelBuilder.Entity<sysTbl_Document>(entity =>
    //    {
    //        entity.Property(e => e.documentId).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();
    //        entity.Property(e => e.transToCustomer).HasDefaultValueSql("((0))");
    //    });

    //    modelBuilder.Entity<sysTbl_Menu>(entity =>
    //    {
    //        entity.Property(e => e.menuId).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.forApp).HasDefaultValueSql("((0))");
    //        entity.Property(e => e.forRoot).HasDefaultValueSql("((0))");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.menuLevel).HasDefaultValueSql("((0))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();
    //        entity.Property(e => e.sortOrder).HasDefaultValueSql("((0))");
    //    });

    //    modelBuilder.Entity<sysTbl_Menu_Permission>(entity =>
    //    {
    //        entity.Property(e => e.Id).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.forRoot).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();

    //        entity.HasOne(d => d.menu).WithMany(p => p.sysTbl_Menu_Permission).HasConstraintName("FK_sysTbl_Menu_Permission_menuId");
    //    });

    //    modelBuilder.Entity<sysTbl_NotificationToken>(entity =>
    //    {
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //    });

    //    modelBuilder.Entity<sysTbl_RefreshToken>(entity =>
    //    {
    //        entity.Property(e => e.refreshTokenId).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getutcdate())");
    //        entity.Property(e => e.isOnApp).HasDefaultValueSql("((0))");
    //        entity.Property(e => e.isValidated).HasDefaultValueSql("((0))");
    //    });

    //    modelBuilder.Entity<sysTbl_Role>(entity =>
    //    {
    //        entity.Property(e => e.roleId).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();
    //    });

    //    modelBuilder.Entity<sysTbl_Role_Menu>(entity =>
    //    {
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();

    //        entity.HasOne(d => d.menu).WithMany(p => p.sysTbl_Role_Menu).HasConstraintName("FK_menuId_sysTbl_Menu");

    //        entity.HasOne(d => d.role).WithMany(p => p.sysTbl_Role_Menu).HasConstraintName("FK_roleId_sysTbl_Role");
    //    });

    //    modelBuilder.Entity<sysTbl_Role_Menu_Permission>(entity =>
    //    {
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();

    //        entity.HasOne(d => d.menu_Permission).WithMany(p => p.sysTbl_Role_Menu_Permission).HasConstraintName("FK_RoleMenuPermission_MenuPermission_UpdateDelete");

    //        entity.HasOne(d => d.role).WithMany(p => p.sysTbl_Role_Menu_Permission).HasConstraintName("FK_RoleMenuPermission_Role_UpdateDelete");
    //    });

    //    modelBuilder.Entity<sysTbl_User>(entity =>
    //    {
    //        entity.Property(e => e.userId).HasDefaultValueSql("([dbo].[sysFunc_AutoGenerateId](rand()))");
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.isOnline).HasDefaultValueSql("((0))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();
    //    });

    //    modelBuilder.Entity<sysTbl_User_Role>(entity =>
    //    {
    //        entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
    //        entity.Property(e => e.isActived).HasDefaultValueSql("((1))");
    //        entity.Property(e => e.row_version)
    //            .IsRowVersion()
    //            .IsConcurrencyToken();

    //        entity.HasOne(d => d.role).WithMany(p => p.sysTbl_User_Role).HasConstraintName("FK_roleId_sysTbl_Role_sysTbl_User_Role");

    //        entity.HasOne(d => d.user).WithMany(p => p.sysTbl_User_Role).HasConstraintName("FK_userId_sysTbl_User_sysTbl_User_Role");
    //    });

    //    OnModelCreatingPartial(modelBuilder);
    //}

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}