// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

public partial class sysTbl_Menu
{
    [Key]
    public long menuId { get; set; }

    public long? parentId { get; set; }

    [StringLength(255)]
    public string menuName { get; set; }

    public byte? menuLevel { get; set; }

    public byte? sortOrder { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string menuIcon { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string languageKey { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string menuComponent { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string navigateUrl { get; set; }

    public bool? forRoot { get; set; }

    public bool? forApp { get; set; }

    public bool? isActived { get; set; }

    [Precision(0)]
    public DateTime? createdDate { get; set; }

    public long? createdBy { get; set; }

    [Precision(0)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    public byte[] row_version { get; set; }

    [InverseProperty("menu")]
    public virtual ICollection<sysTbl_Menu_Permission> sysTbl_Menu_Permission { get; set; } = new List<sysTbl_Menu_Permission>();

    [InverseProperty("menu")]
    public virtual ICollection<sysTbl_Role_Menu> sysTbl_Role_Menu { get; set; } = new List<sysTbl_Role_Menu>();
}