// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

public partial class sysTbl_Menu_Permission
{
    [Key]
    public long Id { get; set; }

    [Required]
    [StringLength(100)]
    public string MP_Name { get; set; }

    [Required]
    public string MP_Description { get; set; }

    public long menuId { get; set; }

    public string photo { get; set; }

    public bool? forRoot { get; set; }

    public bool? isActived { get; set; }

    [Precision(0)]
    public DateTime? createdDate { get; set; }

    public long? createdBy { get; set; }

    [Precision(0)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    public byte[] row_version { get; set; }

    [ForeignKey("menuId")]
    [InverseProperty("sysTbl_Menu_Permission")]
    public virtual sysTbl_Menu menu { get; set; }

    [InverseProperty("menu_Permission")]
    public virtual ICollection<sysTbl_Role_Menu_Permission> sysTbl_Role_Menu_Permission { get; set; } = new List<sysTbl_Role_Menu_Permission>();
}