// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

public partial class sysTbl_Application
{
    [Key]
    public long id_app { get; set; }

    [StringLength(20)]
    public string app_code { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string name_file { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string app_version { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CHPlay_version { get; set; }

    [StringLength(500)]
    public string link_url { get; set; }

    public int? update_type { get; set; }

    [Precision(0)]
    public DateTime? change_date { get; set; }

    public long? createdBy { get; set; }

    public byte[] row_version { get; set; }
}