// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

public partial class sysTbl_NotificationToken
{
    [Key]
    [StringLength(200)]
    [Unicode(false)]
    public string Token { get; set; }

    [StringLength(100)]
    public string DeviceName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DeviceModelName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DeviceBrand { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string DeviceType { get; set; }

    public bool? isActived { get; set; }
}