// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

[Index("userName", Name = "UC_sysTbl_User_userName", IsUnique = true)]
public partial class sysTbl_User
{
    [Key]
    public long userId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string userName { get; set; }

    [StringLength(100)]
    public string fullName { get; set; }

    [Required]
    [StringLength(100)]
    public string userPassword { get; set; }

    public bool? isOnline { get; set; }

    public bool? isActived { get; set; }

    [Precision(0)]
    public DateTime? createdDate { get; set; }

    public long? createdBy { get; set; }

    [Precision(0)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? lastLoginOnWeb { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? lastLoginOnApp { get; set; }

    public byte[] row_version { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<sysTbl_User_Role> sysTbl_User_Role { get; set; } = new List<sysTbl_User_Role>();
}