// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

[PrimaryKey("roleId", "menuId")]
public partial class sysTbl_Role_Menu
{
    [Key]
    public long roleId { get; set; }

    [Key]
    public long menuId { get; set; }

    public bool? isActived { get; set; }

    [Precision(0)]
    public DateTime? createdDate { get; set; }

    public long? createdBy { get; set; }

    [Precision(0)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    public byte[] row_version { get; set; }

    [ForeignKey("menuId")]
    [InverseProperty("sysTbl_Role_Menu")]
    public virtual sysTbl_Menu menu { get; set; }

    [ForeignKey("roleId")]
    [InverseProperty("sysTbl_Role_Menu")]
    public virtual sysTbl_Role role { get; set; }
}