// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

[Index("commonMasterName", Name = "UC_sysTbl_CommonMaster_commonMasterName", IsUnique = true)]
public partial class sysTbl_CommonMaster
{
    [Key]
    [StringLength(3)]
    [Unicode(false)]
    public string commonMasterCode { get; set; }

    [Required]
    [StringLength(255)]
    public string commonMasterName { get; set; }

    public bool? forRoot { get; set; }

    public bool? isActived { get; set; }

    [Precision(0)]
    public DateTime? createdDate { get; set; }

    public long? createdBy { get; set; }

    [Precision(0)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    public byte[] row_version { get; set; }

    [InverseProperty("commonMasterCodeNavigation")]
    public virtual ICollection<sysTbl_CommonDetail> sysTbl_CommonDetail { get; set; } = new List<sysTbl_CommonDetail>();
}