// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

[Index("roleCode", Name = "UC_sysTbl_Role_roleCode", IsUnique = true)]
[Index("roleName", Name = "UC_sysTbl_Role_roleName", IsUnique = true)]
public partial class sysTbl_Role
{
    [Key]
    public long roleId { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string roleCode { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string roleName { get; set; }

    [StringLength(255)]
    public string roleDescription { get; set; }

    public bool? isActived { get; set; }

    [Precision(0)]
    public DateTime? createdDate { get; set; }

    public long? createdBy { get; set; }

    [Precision(0)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    public byte[] row_version { get; set; }

    [InverseProperty("role")]
    public virtual ICollection<sysTbl_Role_Menu> sysTbl_Role_Menu { get; set; } = new List<sysTbl_Role_Menu>();

    [InverseProperty("role")]
    public virtual ICollection<sysTbl_Role_Menu_Permission> sysTbl_Role_Menu_Permission { get; set; } = new List<sysTbl_Role_Menu_Permission>();

    [InverseProperty("role")]
    public virtual ICollection<sysTbl_User_Role> sysTbl_User_Role { get; set; } = new List<sysTbl_User_Role>();
}