// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace NewPrjESDEDIBE.Models;

public partial class sysTbl_CommonDetail
{
    [Key]
    public long commonDetailId { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string commonMasterCode { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string commonDetailCode { get; set; }

    [Required]
    [StringLength(255)]
    public string commonDetailName { get; set; }

    public bool? isActived { get; set; }

    [Precision(0)]
    public DateTime? createdDate { get; set; }

    public long? createdBy { get; set; }

    [Precision(0)]
    public DateTime? modifiedDate { get; set; }

    public long? modifiedBy { get; set; }

    public byte[] row_version { get; set; }

    [ForeignKey("commonMasterCode")]
    [InverseProperty("sysTbl_CommonDetail")]
    public virtual sysTbl_CommonMaster commonMasterCodeNavigation { get; set; }
}